# Generated by Django 4.2.4 on 2023-08-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_board_name_alter_board_column_alter_column_card'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='board',
            field=models.ManyToManyField(blank=True, to='board.board', verbose_name='Доски'),
        ),
    ]
