# Generated by Django 4.2.4 on 2023-08-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_board_name_alter_board_column_alter_column_card'),
        ('user', '0002_alter_customuser_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='test',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='board',
            field=models.ManyToManyField(blank=True, to='board.board'),
        ),
    ]
