# Generated by Django 4.2.4 on 2023-08-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.BigIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.BigIntegerField()),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('card', models.ManyToManyField(blank=True, to='board.card')),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.BigIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('column', models.ManyToManyField(blank=True, to='board.column')),
            ],
        ),
    ]
