# Generated by Django 4.2.4 on 2023-08-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='board',
            name='column',
            field=models.ManyToManyField(blank=True, to='board.column'),
        ),
        migrations.AlterField(
            model_name='column',
            name='card',
            field=models.ManyToManyField(blank=True, to='board.card'),
        ),
    ]
